FROM ubuntu:18.04

RUN useradd -s /bin/bash -m john
RUN useradd -s /bin/bash -m jack
RUN useradd -s /bin/bash -m ryan
RUN useradd -s /bin/bash -m max
RUN useradd -s /bin/bash -m rex
RUN useradd -s /bin/bash -m nick
RUN useradd -s /bin/bash -m ronald
RUN useradd -s /bin/bash -m lioali

RUN usermod -a -G sudo ryan
RUN usermod -a -G audio ryan
RUN usermod -a -G users ryan

USER root
WORKDIR /root


